version: "3.8"
services:
  rabbitmq: 
    container_name: "rabbitmq"
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      # rabbitmq instance
      - '5672:5672'
      # web interface  
      - '15672:15672'